### ISSUE TITLE
Generate message payload description from XML documentation

### ISSUE THREAD

**Issue by Gabrielbdd** [tehmantra/saunter#131]
It would be nice if XML documentation (ex: summary tags) generated corresponding "description" attributes on the message payload object.

For example, given this message:
```csharp
public class UserSignUpMessage
{
  /// <summary>
  /// Email of the user
  /// </summary>
  public string Email { get; set; }
}
```

The generated message payload would be:
```yaml
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          email:
            type: string
            description: Email of the user
```

I only tested that using "summary", so I'm not sure if something like that is already possible with other kind of comment and just not documented yet.

Anyways, I think it would be a great addition 😄
